---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver on debian node only
    apt:
     name: apache2
     state: present
     
  - name: i want to install webserver on redhat node only
    yum:
      name: httpd
      state: present