---
- name: give the tomcat group ownership
  file:
    path: /opt/tomcat
    state: directory
    group: tomcat
    recurse: yes

- name: give the tomcat group read access to the conf
  file:
    path: /opt/tomcat/conf
    state: directory
    mode:  g+r
    recurse: yes

- name: give the tomcat group execute access to the conf
  file:
    path: /opt/tomcat/conf/
    state: directory
    mode: g+x
    owner: tomcat

- name: Make the tomcat user the owner of the work
  file:
    path: /opt/tomcat/work/
    state: directory
    recurse: yes
    owner: tomcat
  
- name: Make the tomcat user the owner of the temp
  file:
    path: /opt/tomcat/temp/
    state: directory
    recurse: yes
    owner: tomcat

- name: Make the tomcat user the owner of the logs
  file:
    path: /opt/tomcat/logs/
    state: directory
    recurse: yes
    owner: tomcat
  
